version: '3.1'
services:
  front:
    build: .
    image: conorcallanan/formulastat-back
    ports:
      - "8081:8081"
    depends_on:
      - back
  back:
    build: ../go-backend
    image: conorcallanan/formulastat-front
    ports:
     - "3333:3333"
    depends_on:
      - db
  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: cars
    expose:
      - "5433"
    ports: 
      - "5433:5433"
    volumes:
      - db-data:/docker-dev-volumes/formulastat
    command: -p 5433

volumes:
  db-data: